# Generated by Django 4.2.6 on 2023-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_tages_product_tags_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
